### ISSUE TITLE
"Edit on GitHub" links do not work

### ISSUE THREAD

**Issue by malaire** [getopenmono/monodocs#3]
For example on page (1) there is link (2) which does not work.

(1) http://developer.openmono.com/en/latest/getting-started/install.html
(2) https://github.com/getopenmono/monodocs/blob/master/getting-started/install.rst

**Comment by stoffera** [comment]
The _Edit on Github_ button is automatically created by our documentation system (readthedocs.org) and inserted into all pages. ReadTheDocs.org expects source files to be [rST](http://docutils.sourceforge.net/rst.html), not [Markdown](https://daringfireball.net/projects/markdown/) as we use.

To change this requires altering the ReadTheDocs template (I think). Fixing the link would be nice, but I prioritize other tasks at the moment. (Like adding more documentation and updating/fixing software issues.)

**Comment by stoffera** [comment]
I just fixed this by editing the conf.py :-)
