### ISSUE TITLE
"Using Monokiosk" needs to be updated for monoprog 0.8.0

### ISSUE THREAD

**Issue by malaire** [getopenmono/monodocs#4]
"Using Monokiosk"[1] should be updated for monoprog 0.8.0 which is much easier to use - no need for bootloader mode, so whole section about that can be removed.

[1] http://developer.openmono.com/en/latest/getting-started/using_monokiosk.html

**Comment by stoffera** [comment]
Hi @malaire, you are right! We have _a lot_ on our minds right now. So things like that easily miss our attention.

To remove the text is quite straight forward, so we would be delighted if you would submit a pull request on the matter. If you don't think it is something you wish to engage in, that is perfectly fine. We will eventually update the article ourselves. However, we will appreciate any kind of help, if you are interested?

**Comment by malaire** [comment]
I don't know how to do pull requests, but learning that is on my long todo-list.

**Comment by stoffera** [comment]
section is removed
